#+STARTUP: hideblocks
* Notes
** TODO Planned Tweaks
   - [ ] use ENTER to follow links
   - [ ] move mode specific hotkeys from general to use-package
   - [ ] blacken for python mode
   - [ ] Remove annoying lisp warning and char number warnings for flycheck
   - [ ] Move org-files to dropbox ;; just dragging my feet
   - [ ] don't delete scratch buffer zzamboni
   - [ ] learn about bookmarks
   - [ ] improve documentation of this file
   - [ ] Instead of 'catapult use when microsoft, so I don't need to update my config
   - [ ] reduce start time [[https://www.reddit.com/r/emacs/comments/3kqt6e/2_easy_little_known_steps_to_speed_up_emacs_start/][1]] [[https://blog.d46.us/advanced-emacs-startup/][2]]
   - [ ] Org Blog w/ [[https://ox-hugo.scripter.co/][ox-hugo]]. [[https://www.reddit.com/r/orgmode/comments/gcex8p/creating_a_blog_with_orgmode/][Reddit Post]]
   - [ ] LSP instead of elpy
   - [ ] Figure out where & how windows knows where my emacs is
   - [ ] PDF-viewer ;; seems like a drag on windows. doc-viewer let's me at least see the text
   - [ ] hydra for [[https://github.com/abo-abo/hydra/wiki/Emacs][outline]]
   - [ ] fix ediff
   - [ ] add hooks more elegantly w/ general
   - [ ] babel installs (R)
   - [ ] [[http://www.cachestocaches.com/2017/3/complete-guide-email-emacs-using-mu-and-/][email]]
   - [X] Figure out pomodoro
   - [X] gitgutter
   - [X] [[https://github.com/bastibe/org-journal][org-journal]]
   - [X] Config Shackle (do I need to? I feel like I've been able to supress a lot as of late)
   - [X] Default new todo bullet to TODO not inprogress
   - [X] customize telephone line [[https://www.reddit.com/r/emacs/comments/7e7xzg/telephoneline_theming_question/][colors]] to match theme ;; Defaults look better than the starting custom
   - [X] ask about org-habit going away after tweaks ;; decided that It's not a big deal
   - [X] move scheduled to todo
   - [X] hydra for themes solved w/ counsel-load-file
   - [X] Fix Agenda
   - [X] [[https://www.reddit.com/r/emacs/comments/4n0n8o/what_is_the_best_emacs_mode_line_package/][some sort of mode line]]. [[https://github.com/dbordak/telephone-line][Telephone-line]] looks promising
   - [X] Tramp: Fix ivy "c:" problem, or just make custom function around it
   - [X] Custom paths
   - [X] figure out lispy (I just went w/ lispyville)
   - [X] Make sure next buffer and last buffer only do real files
   - [X] move w/ evil in agenda
   - [X] magit consider j and k 
   - [X] spell-fu ;; why not in melpa? aspell w/ wierd packman install
   - [X] make this an org file
   - [ ] vim bracket buffer movement
   - [ ] org make todotype selection easier
   - [ ] Treemacs (do I need this?) ;; no
   - [ ] Use [[https://github.com/alphapapa/org-super-agenda][org-super-agenda]]
   - [ ] ace by abo-abo? Probably more than I need
** Inspiration + links
   - [[https://www.youtube.com/watch?v=49kBWM3RQQ8&list=PL9KxKa8NpFxIcNQa9js7dQQIHc81b0-Xg&index=1][Using Emacs videos]]
   - Originally inspaired by based on [[https://huytd.github.io/emacs-from-scratch.html#orgf713fce][this]] implementation 
   - Kwrooijen's [[https://github.com/kwrooijen/.emacs.d/tree/40e0054b012814fd1550e3c6648af4a22e73df72][implmentation]]. Uses evil, use-package, and many abo-abo. 
   - Emacs Adventures [[https://github.com/amolgawai/emacsadventures/tree/92578a5b5bf71ccc7f2e1859edefaa97d8d51df1/config][robust emacs config]] 
   - [[https://sam217pa.github.io/2016/09/23/keybindings-strategies-in-emacs/][Key bindings article]]
   - [[https://blog.aaronbieber.com/2016/09/24/an-agenda-for-life-with-org-mode.html][Aaron Bieber]] the guy who convinced me to try Evil. I steal from his Agenda setup
   - [[https://github.com/angrybacon/dotemacs/blob/master/dotemacs.org][This one]] is beautiful. Found it when investigating mode lines
   - [[https://github.com/noahfrederick/dots/blob/master/emacs/emacs.org][Nox]] has an org set-up in his use-package
   - [[https://github.com/zzamboni/dot-emacs/blob/master/init.org][zzamboni]] has a great literate config. Lots of it considers writing
* Setup
** Paths
   I use multiple computers. This allows me to update paths globally for each of my machines.
 #+begin_src emacs-lisp
      (setq workstation 'catapult) ;; options: catapult, personal_macbook

      (setq user-full-name "Andrew Kraemer")
      (setq user-mail-address "andrew.h.kraemer@gmail.com")

      (cond ((eq window-system 'w32)
	     (setq ak/custpath-home "c:/Users/akraemer/"
		   ak/custpath-dropbox-org "c:/Users/akraemer/Dropbox/org/"
		   ak/custpath-phone-notes "c:/Users/akraemer/Dropbox/org/phone_inbox.org"
		   ak/custpath-journal-path "c:/Users/akraemer/Dropbox/journal/"
		   ak/custpath-emacsd "c:/emacs/.emacs.d/"
		   ak/custpath-org-notes "c:/emacs/notes/"
		   ak/custpath-py-default-env "c:/Users/akraemer/Anaconda3/envs/py37"
		   ak/custpath-flake8 "c:/Users/akraemer/Anaconda3/Scripts/flake8.exe"
		   ak/custpath-aspell "c:/msys64/mingw64/bin/aspell.exe"))
	    ((eq window-system 'darwin)
	     (setq ak/custpath-home "/Users/AndrewKraemer/"
		   ak/custpath-dropbox-org "/Users/AndrewKraemer/Dropbox/org/"
		   ak/custpath-phone-notes "/Users/AndrewKraemer/Dropbox/org/phone_inbox.org"
		   ak/custpath-journal-path "/Users/AndrewKraemer/Dropbox/journal/"
		   ak/custpath-emacsd "~/.emacs.d/"
		   ak/custpath-org-notes "~/emacs/notes/"
		   ak/custpath-py-default-env "/Users/AndrewKraemer/anaconda3/envs/py37"
		   ;; ak/custpath-flake8 "~/Users/AndrewKraemer/Anaconda3/Scripts/flake8.exe"
		   ak/custpath-aspell "/usr/local/bin/aspell")))
 #+end_src

 #+RESULTS:
 : /usr/local/bin/aspell

* Preferences
** TODO make this better documented
 #+begin_src emacs-lisp
   ;;; Code:
   ;; Minimal UI
   (scroll-bar-mode  -1)
   (tool-bar-mode    -1)
   (tooltip-mode     -1)
   (blink-cursor-mode 0)
   (fringe-mode 0)
   (setq initial-scratch-message nil)
   (setq ring-bell-function 'ignore)
   (setq redisplay-dont-pause t ;; Scrolling smoothness
     scroll-margin 1
     scroll-step 1
     scroll-conservatively 10000
     scroll-preserve-screen-position 1)
   (setq temporary-file-directory (concat ak/custpath-emacsd "tmp")) ;; Don't save flycheck locally

   ;; standardizes all yes/no quetions to y/n.
   (fset 'yes-or-no-p 'y-or-n-p)

   ;; Show matching parens
   (setq show-paren-delay 0)
   (show-paren-mode 1)

   ;;match parens automatically
   (electric-pair-mode +1)

   ;; Pretty lambda symbol
   (global-prettify-symbols-mode 1)
 #+end_src

 #+RESULTS:
 : t

    Org mode was being very slow on my windows machine, so I found [[https://www.reddit.com/r/emacs/comments/55ork0/is_emacs_251_noticeably_slower_than_245_on_windows/d8cmm7v/][this]] solution to improve garbage collection.
 #+begin_src emacs-lisp
   (when (eq window-system 'w32)
     (setq gc-cons-threshold (* 511 1024 1024))
     (setq gc-cons-percentage 0.5)
     (run-with-idle-timer 5 t #'garbage-collect)
     (setq garbage-collection-messages nil))
 #+end_src

 #+RESULTS:
 : t

    Windows doesn't have a super key, so I remap the windows key to super. The problem is that the windows key often can't be overridden. I don't use it often, so I might revert.
#+begin_src emacs-lisp
    (when (eq window-system 'w32)
      (setq w32-pass-lwindow-to-system nil)
      (setq w32-lwindow-modifier 'super) )
#+end_src

* Font
 TODO base off of current machine name 
#+begin_src emacs-lisp
  ;; (set-face-attribute 'default nil :family "Consolas" :height 110)
  ;; (set-face-attribute 'default nil :family "Hack" :height 105)
  (if (eq window-system 'w32)
      (set-face-attribute 'default nil
			  :family "Source Code Pro"
			  :weight 'Regular
			  ;; :weight 'bold
			  ;; :width 'normal
			  :height 107)
      (set-face-attribute 'default nil
			  :family "Source Code Pro"
			  :weight 'normal
			  ;; :weight 'bold
			  ;; :width 'normal
			  :height 140))
#+end_src

#+RESULTS:

* Theme / UI / Modeline
  I love nord
   - Theme toggling with counsel-load-theme use C-M-n / C-M-p to preview
#+begin_src emacs-lisp
  (use-package doom-themes
    :ensure t
    :config (load-theme 'doom-nord t))

;; (use-package color-theme-sanityinc-tomorrow
;;   :ensure t
;;   :config
;;   (load-theme 'sanityinc-tomorrow-eighties t))
#+end_src

  This modeline replacement is clean, light, and evil friendly.
#+begin_src emacs-lisp
 (use-package telephone-line
  :init (telephone-line-mode 1))
#+end_src

#+RESULTS:

* Winner
  Winner allows me to iterate through previous window configurations. I've got some files listed to ignore as well.
#+begin_src emacs-lisp
(use-package winner
  :init (setq winner-boring-buffers
        '("*Completions*"
          "*Compile-Log*"
          "*inferior-lisp*"
          "*Fuzzy Completions*"
          "*Apropos*"
          "*dvc-error*"
          "*Help*"
          "*cvs*"
          "*Buffer List*"
          "*Ibuffer*"))
  :config (winner-mode 1))
#+end_src

* Shackle
  Emacs will pop files up all over the place. This package helps reduce the insanity that results from this. I haven't done a comparison of how this changes the pop ups, but I get a sense that they are now more manageable
#+begin_src emacs-lisp
  (use-package shackle
    :ensure t
    :defer t
    :config
    ;; (setq shackle-default-rule '(:select t))
    (shackle-mode t))
#+end_src

#+RESULTS:
: t

* Files
  Stop files from saving temporary files everywhere
#+begin_src emacs-lisp
(use-package 
  :init
  ;; Backup ~ files in seperate directory
  (setq backup-directory-alist `(("." . ,(concat ak/custpath-emacsd "backups"))))
  ;; No confirmation when creating new buffer
  (setq confirm-nonexistent-file-or-buffer nil))
#+end_src

#+RESULTS:

* Expand Region
  when you start on a word you can press `C-=` to expand to sentace/ line. Very helpful for mass grabbing. Very highly rated from what I've read
#+begin_src emacs-lisp
(use-package expand-region 
  :ensure t)
#+end_src

#+RESULTS:

* Evil
#+begin_src emacs-lisp
;; Vim mode
(use-package evil
  :ensure t
   ;; c-u to scroll up
  :init
  (setq evil-want-C-u-scroll t)
  :config
  (evil-mode 1)
  (add-hook 'prog-mode-hook #'turn-on-evil-mode))

(use-package evil-surround
  :ensure t
  :config
  (global-evil-surround-mode 1))

(use-package evil-commentary
  :ensure t
  :config
  (evil-commentary-mode))

(use-package evil-numbers
  :ensure t)
#+end_src

* Golden Ratio
  When I'm coding there is usally a file that I'm focusing on. Golden ratio allows me to balance the window sizes based on the golden ratio
#+begin_src emacs-lisp
  (use-package golden-ratio
    :ensure t)
#+end_src
 
* Ivy, Counsel, Swiper
  - Hide star buffers w/ ivy-ignore buffers. Use C-c C-a to toggle back. Ref [[https://github.com/abo-abo/swiper/issues/644][here]].
#+begin_src emacs-lisp
  (use-package ivy
    :ensure t
    :init
    (setq ivy-use-virtual-buffers t
	  enable-recursive-minibuffers t
          ivy-initial-inputs-alist nil ;; don't use ^ w/ ivy M-x 
	  ivy-re-builders-alist
	    '((swiper . regexp-quote)
	      (t      . ivy--regex-fuzzy)))
    :config
    (setq ivy-ignore-buffers '("\\` " "\\`\\*")) ;; hide star buffers note above
    (ivy-mode 1))

  ;; fuzzy matching for ivy
  (use-package flx
    :ensure t)

  (use-package counsel
    :ensure t)
#+end_src

#+RESULTS:

* Company
   Auto-completion
  - TODO move this to the general section
#+begin_src emacs-lisp
  (use-package company
    :hook
    (after-init . global-company-mode)
    :bind
    ;; make company completion work w/ vimkeys
    (:map company-active-map)
    ("C-n" . company-select-next-or-abort)
    ("C-p" . company-select-previous-or-abort))
#+end_src

#+RESULTS:

* Magit
#+begin_src emacs-lisp
  (use-package magit
    :ensure t)
  
  (use-package evil-magit
    :after magit)

  (use-package git-gutter
    :ensure t
    :config
    (global-git-gutter-mode 't)
    :diminish git-gutter-mode)
#+end_src

#+RESULTS:

* Projectile
#+begin_src emacs-lisp
   (use-package projectile
     :ensure t
     :init
     (setq projectile-require-project-root nil)
     (setq projectile-completion-system 'ivy)
     :config
     (projectile-mode 1))

   (use-package counsel-projectile
    :ensure t
    :config
    (counsel-projectile-mode))
#+end_src

#+RESULTS:
: t

* Org
 
 #+begin_src emacs-lisp
   (use-package org-bullets
     :ensure t
     :config
     (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))

   ;; better lists http://www.howardism.org/Technical/Emacs/orgmode-wordprocessor.html

   (with-eval-after-load 'org (setq org-agenda-files
				   `(,ak/custpath-org-notes ,ak/custpath-phone-notes)))

   ;; Org-Todos
   (setq evil-org-key-theme '(textobjects navigation additional insert todo))

   ;; order priority for sorting
   (setq org-todo-keywords
	 (quote ((sequence "IN_PROGRESS(i)" "NEXT(n)" "TODO(t)" "WAITING(w@/)" "DONE(d)"))))

   (setq org-refile-targets '(
			      (nil :maxlevel . 4)             ; refile to headings in the current buffer
			      (org-agenda-files :maxlevel . 4) ; refile to any of these files
			      ))

   ;; Org-Capture
   (defvar my/org-meeting-template "** Meeting about %^{something}
     SCHEDULED: %<%Y-%m-%d %H:%M>
     ,*Attendees:*
     - [X] Nick Anderson
     - [ ] %?
     ,*Agenda:*
     -
     -
     ,*Notes:*
     ")

   (setq org-capture-templates
       `(;; Note the backtick here, it's required so that the defvar based tempaltes will work!
	 ;;http://comments.gmane.org/gmane.emacs.orgmode/106890

	 ("t" "To-do" entry (file+headline ,(concat ak/custpath-org-notes "gtd.org") "Inbox")
	   "** TODO [#%^{priority}] %^{Task Description}" :prepend t)
	 ("c" "To-do Link" entry (file+headline ,(concat ak/custpath-org-notes "gtd.org") "Inbox")
	   "** TODO [#%^{priority}] %A \n:PROPERTIES:\n:Created: %U\n:Source: %a\n:END:\n%?"
	   :prepend t)
	 ("m" "Meeting" entry (file+headline ,(concat ak/custpath-org-notes "meetings.org") "Meeting Notes")
	  ,my/org-meeting-template)
   ))

#+end_src

#+RESULTS:
| t | To-do      | entry | (file+headline c:/emacs/notes/gtd.org Inbox) | ** TODO [#%^{priority}] %^{Task Description} | :prepend | t |
| c | To-do Link | entry | (file+headline c:/emacs/notes/gtd.org Inbox) | ** TODO [#%^{priority}] %A                   |          |   |


** Pomodoro
 #+begin_src emacs-lisp
   ;; Org-Pomodoro ;; https://github.com/yanivdll/.emacs.d/blob/master/config.org
   (use-package org-pomodoro
     :ensure t
     :config (setq org-pomodoro-play-sounds 1
		   org-pomodoro-finished-sound "c:/Users/akraemer/Dropbox/org/sounds/tone.wav"
		   org-pomodoro-long-break-sound "c:/Users/akraemer/Dropbox/org/sounds/tone.wav"
		   org-pomodoro-short-break-sound "c:/Users/akraemer/Dropbox/org/sounds/tone.wav"

		   ;; https://github.com/marcinkoziej/org-pomodoro/issues/29#issuecomment-129608240
		   ;; to control volume I'd need to have it come from a different player
		   ;; org-pomodoro-audio-player "mplayer"
		   ;; org-pomodoro-finished-sound-args "-volume 0.3"
		   ;; org-pomodoro-long-break-sound-args "-volume 0.3"
		   ;; org-pomodoro-short-break-sound-args "-volume 0.3"

     ))

   ;;https://emacs.stackexchange.com/a/48352
   ;; required for org-sounds
   (use-package sound-wav
     :ensure t)

   ;; ;; required for sound if on windows
   (use-package powershell
     :if (memq window-system '(w32))
     :ensure t
     :config)
  #+end_src

  #+RESULTS:

#+RESULTS:

** org-download
 #+begin_src emacs-lisp
(use-package org-download
  :ensure t
  :config
  ;; add support to dired
  (add-hook 'dired-mode-hook 'org-download-enable))
 #+end_src
 
 #+RESULTS:
 : t
* org agenda / priority
   This section gets a bit nitty gritty. Look at the [[https://orgmode.org/worg/doc.html][Worg documentation]] for details on these settings.

   Only show details for today when viewing the org agenda. I don't know which one does what, but org-agenda-show-future-repeats is allegedly the most up to date
#+begin_src emacs-lisp
  (with-eval-after-load 'org
    (add-to-list 'org-modules 'org-habit t))

  (setq org-habit-show-all-today t)
  (setq org-habit-show-habits-only-for-today t)
  (setq org-agenda-show-future-repeats 'next)
#+end_src

#+RESULTS:
: next

  Non prioritized tasks will be sorted to d, though I usually make sure to priotize all of my tasks w/ my org capture
#+begin_src emacs-lisp
  (setq org-lowest-priority ?D)
  (setq org-default-priority ?D)
#+end_src

  Customize the order in which tasks appear in the agenda
#+begin_src emacs-lisp
  (setq org-agenda-sorting-strategy
      '((agenda habit-up deadline-up scheduled-up priority-up) ;; show habits, then time, then by priority
	(tags todo-state-up deadline-up) ;; show todo-state then deadlines
	(search category-keep)))
#+end_src

#+RESULTS:
| agenda | habit-up      | deadline-up | scheduled-up | priority-up |
| tags   | todo-state-up | deadline-up |              |             |
| search | category-keep |             |              |             |

  Custom agenda filtering functions modified from [[https://blog.aaronbieber.com/2016/09/24/an-agenda-for-life-with-org-mode.html][Aaron Bieber]] as well as one of my own
#+begin_src emacs-lisp
  (defun air-org-skip-subtree-if-habit ()
    "Skip an agenda entry if it has a STYLE property equal to \"habit\"."
    (let ((subtree-end (save-excursion (org-end-of-subtree t))))
      (if (string= (org-entry-get nil "STYLE") "habit")
	subtree-end
      nil)))

  (defun air-org-skip-subtree-if-priority (priority)
    "Skip an agenda subtree if it has a priority of PRIORITY.
  PRIORITY may be one of the characters ?A, ?B, or ?C."
    (let ((subtree-end (save-excursion (org-end-of-subtree t)))
	(pri-value (* 1000 (- org-lowest-priority priority)))
	(pri-current (org-get-priority (thing-at-point 'line t))))
      (if (= pri-value pri-current)
	subtree-end
      nil)))
      
  (defvar current-date-format "%Y-%m-%d"
    "Format of date to insert with `insert-current-date-time' func
     See help of `format-time-string' for possible replacements")

  (defun ak/org-skip-subtree-if-not-archived-today ()
    "Skip an agenda entry if it was not completed today"
    (concat ":ARCHIVE_TIME: " (format-time-string current-date-format (current-time))))
#+end_src

#+RESULTS:
: air-org-skip-subtree-if-priority


  Settings for the different agenda blocks. Utilizes aairon bieber functions to prevent tasks from appearing multiple times in agenda.
#+begin_src emacs-lisp
  (setq org-agenda-custom-commands
	'(("d" "Daily agenda and all TODOs"
	   ((tags "PRIORITY=\"A\""
		  ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
		   (org-agenda-overriding-header "High-priority unfinished tasks:")))
	    ;; (agenda "" ;; skipped completed habits. I prefer if they stay but are ordered
	    ;; 	  ((org-agenda-span 'day)
	    ;; 	   (org-agenda-skip-function '(and (org-agenda-skip-entry-if 'todo '("NEXT")) (org-agenda-skip-entry-if 'regexp "habit"))) ;; hide completed habits
	    ;; 	   (org-agenda-overriding-header "ALL normal priority tasks:")))
	    (agenda ""
		    ((org-agenda-span 'day)
		     (org-agenda-overriding-header "ALL normal priority tasks:")))
	    (tags (or "PRIORITY=\"B\"" "PRIORITY=\"C\"")
		  ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
		   (org-agenda-overriding-header "Unfinished tasks:")))
	    (alltodo ""
		     ((org-agenda-skip-function '(or (air-org-skip-subtree-if-habit)
						     (air-org-skip-subtree-if-priority ?A)
						     (air-org-skip-subtree-if-priority ?B)
						     (org-agenda-skip-if nil '(scheduled deadline))))
		      (org-agenda-overriding-header "Eventually:"))))
	   ;; ((org-agenda-compact-blocks t)) ;; removes = breaks
	   )
	  ("r" "Day in review"
	     todo "DONE"
	     ;; agenda settings
	     ((org-agenda-files '("c:/emacs/notes/gtd.org_archive"))
	      (org-agenda-start-with-log-mode '(ARCHIVE_TIME))
	      (org-agenda-archives-mode t)
              (org-agenda-skip-function '(org-agenda-skip-entry-if 'notregexp (ak/org-skip-subtree-if-not-archived-today)))
	      (org-agenda-overriding-header "Day in Review"))
	     ;; ("~/org/review/day.html") ;; for export
		  )))
#+end_src

  Custom full screen agenda function modified from [[https://blog.aaronbieber.com/2016/09/24/an-agenda-for-life-with-org-mode.html][Aaron Bieber]]
#+begin_src emacs-lisp
  (defun air-pop-to-org-agenda (&optional split)
    "Visit the org agenda, in the current window or a SPLIT."
    (interactive "P")
    (org-agenda nil "d")
    (when (not split)
    (delete-other-windows)))
#+end_src

* Org Super Agenda
#+BEGIN_SRC emacs-lisp
  ;; (use-package org-super-agenda
  ;;   :config
  ;;   (org-super-agenda-mode))
#+END_SRC

#+RESULTS:
: t

Definition of =my-super-agenda-groups=, my central configuration of super-agenda:

#+BEGIN_SRC emacs-lisp
  ;; (setq my-super-agenda-groups
  ;;       '(;; Each group has an implicit boolean OR operator between its selectors.
  ;; 	;; (:name "Today"  ; Optionally specify section name
  ;; 	;;        :time-grid t  ; Items that appear on the time grid
  ;; 	;;        )
  ;; 	(:name "DEADLINES" :deadline t :order 1)
  ;; 	(:name "Important" :priority "A" :order 2)
  ;; 	(:priority<= "B"
  ;; 		     ;; Show this section after "Today" and "Important", because
  ;; 		     ;; their order is unspecified, defaulting to 0. Sections
  ;; 		     ;; are displayed lowest-number-first.
  ;; 		     :order 2)
  ;; 	(:name "Habits" :habit t :order 3)
  ;; 	(:name "Shopping" :tag "Besorgung" :order 4)
  ;; 	       ;; Boolean AND group matches items that match all subgroups
  ;; 	       ;;  :and (:tag "shopping" :tag "@town")
  ;; 	       ;; Multiple args given in list with implicit OR
  ;; 	       ;;  :tag ("food" "dinner"))
  ;; 	       ;;  :habit t
  ;; 	       ;;  :tag "personal")
  ;; 	(:name "Started" :todo "STARTED" :order 6)
  ;; 	;;(:name "Space-related (non-moon-or-planet-related)"
  ;; 	;;       ;; Regexps match case-insensitively on the entire entry
  ;; 	;;       :and (:regexp ("space" "NASA")
  ;; 	;;                     ;; Boolean NOT also has implicit OR between selectors
  ;; 	;;                     :not (:regexp "moon" :tag "planet")))
  ;; 	(:name "BWG" :tag "@BWG" :order 7)
  ;; 	(:todo "WAITING" :order 9)  ; Set order of this section
  ;; 	(:name "read" :tag "2read" :order 15)
  ;; 	;; Groups supply their own section names when none are given
  ;; 	(:todo ("SOMEDAY" "WATCHING")
  ;; 	       ;; Show this group at the end of the agenda (since it has the
  ;; 	       ;; highest number). If you specified this group last, items
  ;; 	       ;; with these todo keywords that e.g. have priority A would be
  ;; 	       ;; displayed in that group instead, because items are grouped
  ;; 	       ;; out in the order the groups are listed.
  ;; 	       :order 25)
  ;; 	(:name "reward"
  ;; 	       :tag ("reward" "lp")
  ;; 	       :order 100
  ;; 	       )

  ;; 	;; After the last group, the agenda will display items that didn't
  ;; 	;; match any of these groups, with the default order position of 99
  ;; 	)
  ;;       )
#+END_SRC

#+RESULTS:
| :name       | DEADLINES          | :deadline | t           | :order |   1 |
| :name       | Important          | :priority | A           | :order |   2 |
| :priority<= | B                  | :order    | 2           |        |     |
| :name       | Habits             | :habit    | t           | :order |   3 |
| :name       | Shopping           | :tag      | Besorgung   | :order |   4 |
| :name       | Started            | :todo     | STARTED     | :order |   6 |
| :name       | BWG                | :tag      | @BWG        | :order |   7 |
| :todo       | WAITING            | :order    | 9           |        |     |
| :name       | read               | :tag      | 2read       | :order |  15 |
| :todo       | (SOMEDAY WATCHING) | :order    | 25          |        |     |
| :name       | reward             | :tag      | (reward lp) | :order | 100 |

=my-super-agenda()= is a function so that I am able to call the agenda
interactively or within =my-org-agenda()= which is defined further
down below.

#+BEGIN_SRC emacs-lisp
  ;; (defun my-super-agenda ()
  ;;   "generates my super-agenda"
  ;;   (interactive)
  ;;   (org-super-agenda-mode)
  ;;   (let
  ;;       ((org-super-agenda-groups my-super-agenda-groups))
  ;;     (org-agenda nil "a")
  ;;     )
  ;;   )
#+end_src
#+begin_src emacs-lisp
  ;; (setq org-super-agenda-groups
  ;;      '((:name "Next Items"
  ;; 	      :time-grid t
  ;; 	      :tag ("NEXT" "outbox"))
  ;;        (:name "Important"
  ;; 	      :priority "A")
  ;;        (:name "Quick Picks"
  ;; 	      :effort< "0:30")
  ;;        (:priority<= "B"
  ;; 		    :scheduled future
  ;; 		    ;; :order 1)))
#+end_src
#+RESULTS:
| :name       | Next Items  | :time-grid | t      | :tag   | (NEXT outbox) |
| :name       | Important   | :priority  | A      |        |               |
| :name       | Quick Picks | :effort<   | 0:30   |        |               |
| :priority<= | B           | :scheduled | future | :order |             1 |

#+begin_src emacs-lisp
  ;; (org-super-agenda-mode 1) 
  ;; (my-super-agenda)
#+end_src

#+RESULTS:

#+begin_src emacs-lisp
   ;; (let ((org-super-agenda-groups
   ;;       '(;; Each group has an implicit boolean OR operator between its selectors.
   ;; 	 (:name "Today"  ; Optionally specify section name
   ;; 		:time-grid t  ; Items that appear on the time grid
   ;; 		:todo "TODAY")  ; Items that have this TODO keyword
   ;; 	 (:name "Important"
   ;; 		;; Single arguments given alone
   ;; 		:tag "bills"
   ;; 		:priority "A")
   ;; 	 ;; Set order of multiple groups at once
   ;; 	 (:order-multi (2 (:name "Shopping in town"
   ;; 				 ;; Boolean AND group matches items that match all subgroups
   ;; 				 :and (:tag "shopping" :tag "@town"))
   ;; 			  (:name "Food-related"
   ;; 				 ;; Multiple args given in list with implicit OR
   ;; 				 :tag ("food" "dinner"))
   ;; 			  (:name "Personal"
   ;; 				 :habit t
   ;; 				 :tag "personal")
   ;; 			  (:name "Space-related (non-moon-or-planet-related)"
   ;; 				 ;; Regexps match case-insensitively on the entire entry
   ;; 				 :and (:regexp ("space" "NASA")
   ;; 					       ;; Boolean NOT also has implicit OR between selectors
   ;; 					       :not (:regexp "moon" :tag "planet")))))
   ;; 	 ;; Groups supply their own section names when none are given
   ;; 	 (:todo "WAITING" :order 8)  ; Set order of this section
   ;; 	 (:todo ("SOMEDAY" "TO-READ" "CHECK" "TO-WATCH" "WATCHING")
   ;; 		;; Show this group at the end of the agenda (since it has the
   ;; 		;; highest number). If you specified this group last, items
   ;; 		;; with these todo keywords that e.g. have priority A would be
   ;; 		;; displayed in that group instead, because items are grouped
   ;; 		;; out in the order the groups are listed.
   ;; 		:order 9)
   ;; 	 (:priority<= "B"
   ;; 		      ;; Show this section after "Today" and "Important", because
   ;; 		      ;; their order is unspecified, defaulting to 0. Sections
   ;; 		      ;; are displayed lowest-number-first.
   ;; 		      :order 1)
   ;; 	 ;; After the last group, the agenda will display items that didn't
   ;; 	 ;; match any of these groups, with the default order position of 99
   ;; 	 )))
   ;;  (org-agenda nil "a"))

  ;; (use-package org-super-agenda
  ;;   :ensure t
  ;;   :config
  ;;  (setq org-super-agenda-groups '((:name "Today"
  ;; 				  :time-grid t
  ;; 				  :scheduled today)
  ;; 			   (:name "Due today"
  ;; 				  :deadline today)
  ;; 			   (:name "Important"
  ;; 				  :priority "A")
  ;; 			   (:name "Overdue"
  ;; 				  :deadline past)
  ;; 			   (:name "Due soon"
  ;; 				  :deadline future)
  ;; 			   (:name "Waiting"
  ;; 				 :todo "WAIT"))))
#+end_src

#+RESULTS:

* Org-journal
#+begin_src emacs-lisp
 (use-package org-journal
  :ensure t
  :defer t
  :custom
  (org-journal-dir ak/custpath-journal-path)
  (org-journal-date-format "%Y-%m-%d"))
#+end_src

#+RESULTS:
: t

* Babel
#+begin_src emacs-lisp
(org-babel-do-load-languages
'org-babel-load-languages
'((R . t)
    (python . t)))
;; put viz inline by default
(setq org-startup-with-inline-images t)

(use-package ox-pandoc
  :ensure t
  :defer t)
#+end_src

* Code
** Yasnippet
 #+begin_src emacs-lisp
 (use-package yasnippet
   :ensure t
   :defer 2
   :init
   (yas-global-mode 1))

 (use-package yasnippet-snippets
   :ensure t)
 #+end_src

** Python
   Elpy is the python IDE for emacs. I 
 #+begin_src emacs-lisp
 ;; Python
 (use-package elpy
   :ensure t
   :defer t
   :init
     (advice-add 'python-mode :before 'elpy-enable)
     (setq python-shell-interpreter "jupyter"
	python-shell-interpreter-args "console --simple-prompt"
	python-shell-prompt-detect-failure-warning nil)
     (pyvenv-activate ak/custpath-py-default-env)
   :config
     (setq elpy-modules (delq 'elpy-module-flymake elpy-modules)) ;; don't use use flymake
     (add-hook 'elpy-mode-hook 'flycheck-mode) ;; use use flycheck instead
     (when (eq window-system 'w32)
       (setq flycheck-python-flake8-executable ak/custpath-flake8))  ;; Need to install flake8 explicitly on windows
 )
 #+end_src

** hy
 #+begin_src emacs-lisp
 (use-package hy-mode
   :defer t
   :init (add-hook 'hy-mode-hook 'lispyville-mode))
 #+end_src

 #+RESULTS:
 | lispy-mode |

** Lispy
 #+begin_src emacs-lisp
   (use-package lisp;; y
     :disabled
     :ensure t
     :defer t
     :init
       (general-add-hook '(hy-mode-hook lisp-mode-hook emacs-lisp-mode-hook) #'lispy-mode)
       ;; (add-hook 'hy-mode-hook #'lispy-mode)
       ;; (add-hook 'lisp-mode-hook #'lispy-mode)
       ;; (add-hook 'emacs-lisp-mode-hook #'lispy-mode)
   )

   (use-package lispyville
     :ensure t
     :defer t
     :init
       (general-add-hook '(emacs-lisp-mode-hook hy-mode-hook lisp-mode-hook) #'lispyville-mode))
     :config
       (lispyville-set-key-theme '(additional prettify text-objects atom-motions additional-motions commentary slurp/barf-cp additional-wrap))
 #+end_src

 #+RESULTS:

* Tramp
  - Snippet taken from here https://www.emacswiki.org/emacs/Tramp_on_Windows
  - create saved session in putty then use the name like shown below
  - run the following in eshell: "find-file /plink:bort:~/" Need to figure out how to get this to run in counsel-find file or get an easier way to access the vanilla find-file
#+begin_src emacs-lisp
  (use-package tramp
    :ensure t
    :defer t
    :init
     (when (eq window-system 'w32)
       (setq tramp-default-method "plink")
       (setenv "PATH" (concat "c:/Program Files/PuTTY/" ";" (getenv "PATH")))))
#+end_src

* eshell
#+begin_src emacs-lisp
;; eshell config
(defun new-eshell ()
  "Open eshell on bottom of screen."
  (interactive)
  (when (one-window-on-screen-p)
    (let* ((lines (window-body-height))
           (new-window (split-window-vertically (floor (* 0.7 lines)))))
      (select-window new-window)
      (eshell "eshell"))))

(defun one-window-on-screen-p ()
  "Check if there is only one buffer on the screen."
  (= (length (window-list)) 1))
#+end_src

* Checks
** Spelling
   install instructions from [[https://www.reddit.com/r/emacs/comments/8by3az/how_to_set_up_sell_check_for_emacs_in_windows/][this reddit page]]. User thrillsd instructions using mysys2. 
 #+begin_src emacs-lisp
   ;; install aspell w/ msys on windows
   (setq-default ispell-program-name ak/custpath-aspell)
 #+end_src

 #+RESULTS:
 : /usr/local/bin/aspell

** Flycheck
 #+begin_src emacs-lisp
 (use-package flycheck
   :init  (setq flymake-run-in-place nil) ;; don't save flymake locally
   :ensure t)
 #+end_src

* Which-Key
#+begin_src emacs-lisp
(use-package which-key
  :ensure t
  :init
  (setq which-key-separator " ")
  (setq which-key-prefix-prefix "+")
  :config
  (which-key-mode 1))
#+end_src
 
* Writing
** Write Room
   Write room is a package great for narrowing my focus on writing. It takes the full screen, much like your average "distraction free" writing enviornments. It's also nice to use with my helper function C-c f (f for focus) which toggles the narrowing of a sub tree in case I'm working with an unweildy org file
#+begin_src emacs-lisp
  (use-package writeroom-mode
    :ensure t)
#+end_src

** Word Count
   I want to experiment with writing 750 words in my journal a day. The settings below makes sure that I get a word count when I'm using my journal.
#+begin_src emacs-lisp
  (use-package wc-mode
    :ensure t)
#+end_src

#+RESULTS:

* Key Bindings
** General
 #+begin_src emacs-lisp
   ;; Custom keybinding
   (use-package general
     :ensure t
     :config (general-evil-setup) ;; let's me use general-*map keys
	     (general-nvmap
	       ;; replaces C-c with ,
	       "," (general-simulate-key "C-c"))
	     (general-define-key
	       :states '(normal visual)
	       ;; use visual line movement w/ j/k
	       "j" 'evil-next-visual-line
	       "k" 'evil-previous-visual-line
	       ;; globally define 
	       "C-=" 'er/expand-region)
	     (general-define-key
	       :states '(normal viusal)
	       :prefix "g"
	       ;; bind gj and gk
	       "j" 'evil-next-line
	       "k" 'evil-previous-line)
	     (general-define-key
	       :states '(normal visual insert emacs)
	       :prefix "SPC"
	       :non-normal-prefix "M-SPC"
	       "/"  '(swiper :which-key "swiper") ; You'll need counsel package for this ;; consider counsel-git-grep
	       "\\"  '(counsel-rg :which-key "ripgrep") ; You'll need counsel package for this ;; consider counsel-git-grep
	       "TAB" '(spacemacs/alternate-window :which-key "alternate buffer")
	       "SPC" '(counsel-M-x :which-key "M-x")
	       "f"   '(:ignore t :which-key "files")
	       "ff"  '(counsel-find-file :which-key "find files")
	       "fr"  '(counsel-recentf :which-key "recent files")
	       "fs"  '(save-buffer :which-key "save buffer")
	       "ft"  '(ak/ivy-tramp-find-file :which-key "find tramp files")
	       "fh"  '(ak/ivy-home-find-file :which-key "find home files")
	       ;;projects
	       "p"   '(:ignore t :which-key "project")
	       "pc"  '(:keymap projectile-command-map :which-key "commands")
	       "pp"  '(projectile-switch-project :which-key "switch project")
	       "pb"  '(counsel-projectile-switch-to-buffer :which-key "find project file")
	       "pf"  '(counsel-projectile-find-file :which-key "find project file")
	       "pg"  '(projectile-grep :which-key "grep project")
	       "pk"  '(projectile-kill-buffers :which-key "kill all buffers in project")
	       ;; eval
	       "e"   '(:ignore t :which-key "evaluate")
	       "ee"  '(eval-last-sexp :which-key "last expression")
	       "eE"  '(eval-expression :which-key "expression")
	       "eb"  '(eval-buffer :which-key "buffer")
	       "er"  '(eval-region :which-key "region")
	       ;; Buffers
	       "b"   '(:ignore t :which-key "buffers")
	       "bb"  '(ivy-switch-buffer :which-key "buffers list")
	       "bs"  '(ak/go-to-scratch :which-key "open scratch")
	       "bn"  '(switch-to-next-buffer :which-key "next buffer")
	       "bp"  '(switch-to-prev-buffer :which-key "prev buffer")
	       "bd"  '(kill-this-buffer :which-key "delete buffer")
	       "bk"  '(evil-delete-buffer :which-key "delete buffer and window")
	       "bq"  '(ak/save-exit-buffer-list :which-key "quit gtd-files")
	       ;; Window
	       "w"   '(:ignore t :which-key "window")
	       "wl"  '(windmove-right :which-key "move right")
	       "wh"  '(windmove-left :which-key "move left")
	       "wk"  '(windmove-up :which-key "move up")
	       "wj"  '(windmove-down :which-key "move bottom")
	       "wL"  '(evil-window-move-far-right :which-key "shift window right")
	       "wH"  '(evil-window-move-far-left :which-key "shift window left")
	       "wK"  '(evil-window-move-very-top :which-key "shift window up")
	       "wJ"  '(evil-window-move-very-bottom :which-key "shift window bottom")
	       "wv"  '(split-window-right :which-key "split right")
	       "ws"  '(split-window-below :which-key "split bottom")
	       "wo"  '(delete-other-windows :which-key "delete other windows")
	       "wd"  '(delete-window :which-key "delete window")
	       "wg"  '(golden-ratio :which-key "golden ratio")
	       "wc"  '(evil-window-delete :which-key "delete window")
	       ;; "wu"  '(winner-undo :which-key "winner undo")
	       ;; "wU"  '(winner-redo :which-key "winner redo")
	       "ww"  '(writeroom-mode :which-key "writeroom mode")
	       ;; v for view
	       "v"   '(:ignore t :which-key "view")
	       "vc"  '(ivy-push-view :which-key "create view")
	       "vv"  '(ivy-switch-view :which-key "switch view")
	       ;; Org
	       "o"   '(:ignore t :which-key "org")
	       "ob"  '(ak/insert-bable :Which-key "insert bable")
	       "oo"  '(air-pop-to-org-agenda :which-key "open standard agenda")
	       "or"  '(org-agenda :which-key "open review agenda")
	       "oc"  '(org-capture :which-key "org capture")
	       "oj"  '(org-journal-new-entry :which-key "org journal")
	       "op"  '(org-pomodoro :which-key "pomodoro start")
	       "oP"  '(org-clock-out :which-key "pomodoro stop")
	       ;; git
	       "g"   '(:ignore t :which-key "git")
	       "gs"  '(magit-status :which-key "magit status")
	       "ga"  '(magit-stage :which-key "magit add")
	       "gd"  '(magit-dispatch :which-key "magit dispatch")
	       "gi"  '(magit-gitignore :which-key "magit gitignore")
	       "gn"  '(git-gutter:next-hunk :which-key "next hunk")
	       "gp"  '(git-gutter:previous-hunk :which-key "prev hunk")
	       ;; Visual Toggles
	       "t"   '(:ignore t :which-key "ui toggle")
	       "tn"  '(display-line-numbers-mode :which-key "toggle line numbers")
	       "tl"  '(org-toggle-link-display :which-key "toggle how org links show")
	       "tL"  '(visual-line-mode :which-key "toggle line wrap")
	       "tc"  '(flycheck-mode :which-key "toggle flycheck")
	       "ts"  '(flyspell-mode :which-key "toggle flyspell")
	       "tj"  '(json-pretty-print-buffer :which-key "toggle json pretty-print")
	       ;; Flycheck
	       "c"   '(:ignore t :which-key "code check")
	       "cn"  '(flycheck-next-error :which-key "next error")
	       "cp"  '(flycheck-previous-error :which-key "previous error")
	       ;; Others
	       "at"  '(new-eshell :which-key "eshell"))
	     (general-define-key
	       :states '(normal visual insert emacs)
	       :prefix "C-c"
	       ;; Quick open files
	       "c"  '((lambda () (interactive) (find-file (concat ak/custpath-emacsd "myinit.org"))) :which-key "open .emacs")
	       "o"  '((lambda () (interactive) (find-file (concat ak/custpath-org-notes "gtd.org"))) :which-key "open org")
	       "n"  '((lambda () (interactive) (find-file (concat ak/custpath-org-notes "worknotes.org"))) :which-key "open notes")
	       "N"  '((lambda () (interactive) (find-file (concat ak/custpath-dropbox-org "notes.org"))) :which-key "open notes")
	       ;; Vim  number increment
	       "C-="  '(evil-numbers/inc-at-pt :which-key "increment num")
	       "C--"  '(evil-numbers/dec-at-pt :which-key "decrement num"))
	     ;; org agenda (more options here: https://github.com/Somelauw/evil-org-mode/blob/master/evil-org-agenda.el)
	     (general-define-key
		:keymaps 'org-agenda-mode-map
		"j" 'org-agenda-next-line
		"k" 'org-agenda-previous-line
		"u" 'org-agenda-undo
		"n" 'org-agenda-capture
		"p" 'org-pomodoro
		"C" 'org-agenda-clock-in)
	     ;; Org C-c links
	     (general-define-key
		:states '(normal)
		:prefix "C-c"
		:keymaps 'org-mode-map
		"l" 'org-store-link)
	     (general-define-key
		:keymaps 'elpy-mode-map
		"C-c d" 'elpy-send-defun
		"C-c C-a" 'elpy-goto-assignment)
	     (general-define-key
		:keymaps 'org-journal-mode-map
		"C-c C-c" 'ak/save-close-window)
	     (general-define-key
		:keymaps 'org-mode-map
		 ;; Org-Promote
		"M-l" 'org-do-demote
		"M-h" 'org-do-promote
		"M-L" 'org-demote-subtree
		"M-H" 'org-promote-subtree
		"M-k" 'org-move-subtree-up
		"M-j" 'org-move-subtree-down
		"C-c f" 'ak/org-focus-subtree))
 #+end_src

 #+RESULTS:
 : t

** Hydras
*** Zoom text
    Increase text size. Probably want to change the key binding
   #+begin_src emacs-lisp
 (defhydra hydra-zoom (global-map "<f2>")
  "zoom"
  ("+" text-scale-increase "in")
  ("-" text-scale-decrease "out"))
#+end_src 

*** org-outline

*** Windows
    - I'd like to be able to cycle through a number of winner. There are some binding things here that I don't understand yet
#+begin_src emacs-lisp
 (defhydra hydra-winner (global-map "<f2>")
  "Winner"
  ("u" winner-undo "in")
  ("U" winner-redo "out"))
#+end_src

#+RESULTS:
: hydra-winner/body

*** buffers
    This would work on the normal buffer list. I could use something like this to make navigatig the ivy buffers a little easier
#+begin_src emacs-lisp
   (defhydra hydra-buffer-menu (:color pink
			       :hint nil)
    "
  ^Mark^             ^Unmark^           ^Actions^          ^Search
  ^^^^^^^^-----------------------------------------------------------------
  _m_: mark          _u_: unmark        _x_: execute       _R_: re-isearch
  _s_: save          _U_: unmark up     _b_: bury          _I_: isearch
  _d_: delete        ^ ^                _g_: refresh       _O_: multi-occur
  _D_: delete up     ^ ^                _T_: files only: % -28`Buffer-menu-files-only
  _~_: modified
  "
    ("m" Buffer-menu-mark)
    ("u" Buffer-menu-unmark)
    ("U" Buffer-menu-backup-unmark)
    ("d" Buffer-menu-delete)
    ("D" Buffer-menu-delete-backwards)
    ("s" Buffer-menu-save)
    ("~" Buffer-menu-not-modified)
    ("x" Buffer-menu-execute)
    ("b" Buffer-menu-bury)
    ("g" revert-buffer)
    ("T" Buffer-menu-toggle-files-only)
    ("O" Buffer-menu-multi-occur :color blue)
    ("I" Buffer-menu-isearch-buffers :color blue)
    ("R" Buffer-menu-isearch-buffers-regexp :color blue)
    ("c" nil "cancel")
    ("v" Buffer-menu-select "select" :color blue)
    ("o" Buffer-menu-other-window "other-window" :color blue)
    ("q" quit-window "quit" :color blue))
  ;; (define-key Buffer-menu-mode-map "." 'hydra-buffer-menu/body)
#+end_src

#+RESULTS:
: hydra-buffer-menu/body

* My Custom Functions
** go to scratch
 #+begin_src emacs-lisp
 (defun ak/go-to-buffer (buffer)
   "goes to buffer. If buffer does not exist, creates buffer"
   (if (not (get-buffer buffer))
       (generate-new-buffer buffer))
   (switch-to-buffer buffer))

 (defun ak/go-to-scratch ()
   "runs ak/go-to-buffer for scratch file"
   (interactive)
   (ak/go-to-buffer "*buffer*"))
 #+end_src

 #+RESULTS:
 : ak/go-to-scratch

** Alternate buffers
   Stolen from SPC-TAB spacemacs
 #+begin_src emacs-lisp
   (defun spacemacs/alternate-window (&optional window)
     (interactive)
     (let ((current-buffer (window-buffer window)))
       ;; if no window is found in the windows history, `switch-to-buffer' will
       ;; default to calling `other-buffer'
       (switch-to-buffer
	(cl-find-if (lambda (buffer)
		      (not (eq buffer current-buffer)))
		    (mapcar #'car (window-prev-buffers window)))
	nil t)))
 #+end_src

** Insert Bable
#+begin_src emacs-lisp
 (defun ak/insert-bable ()
   "Insert src_sections for viz in orgmode."
   (interactive)
   (insert "#+begin_src "
           (read-string "Enter Language (R, python, lisp): ")
           (if (equal (read-string "Return Viz (y/n) ") "y")
               " :results output graphics :file img.png"
             ""))
   (insert "\n \n#+end_src"))
#+end_src

#+RESULTS:
: ak-insert-bable

** Tramp Find File
   Counsel-find file wasn't letting me go back to ~/, so I made a function to force it
 #+begin_src emacs-lisp
   (defun ak/ivy-tramp-find-file ()
     "find-file with Tramp. Ex: '/plink:bort:~/'. See tramp note to setup"
     (interactive)
     (let ((tramp-path (concat "/" tramp-default-method ":")))
       (counsel-find-file tramp-path)))
 #+end_src

 #+RESULTS:
 : ak/ivy-tramp-find-file

** Find File Home
   Counsel-find file wasn't letting me go back to ~/, so I made a function to force it
 #+begin_src emacs-lisp
   (defun ak/ivy-home-find-file ()
     "find-file with Tramp. Ex: '/plink:bort:~/'. See tramp note to setup"
     (interactive)
     (counsel-find-file ak/custpath-home))
 #+end_src

 #+RESULTS:
 : ak/ivy-home-find-file

** Save and close window
   Wanted to have something for org-journal that behaves like magit buffer when you C-c C-c
 #+begin_src emacs-lisp
   (defun ak/save-close-window ()
     "find-file with Tramp. Ex: '/plink:bort:~/'. See tramp note to setup"
     (interactive)
     (save-buffer)
     (kill-buffer)
     (delete-window))
 #+end_src

 #+RESULTS:
 : ak/save-close-window

** Focus / unfocus on org bullet
    Toggle org narrow subtreee / show everything
#+begin_src emacs-lisp
  (defun ak/org-focus-subtree ()
    "Toggle org narrow subtreee / show everything"
    (interactive)
    (if (buffer-narrowed-p)
	(widen)
      (org-narrow-to-subtree)))
#+end_src

#+RESULTS:
: ak/org-focus-subtree

** Close all gtd files
    Quickly save and close gtd files to not conflict with other computers
#+begin_src emacs-lisp
(setq gtd-buffer-list '("inbox.org" "gtd.org" "gtd.org_archive" "notes.org" "notes.org_archive" "phone_inbox.org")) ;; custpath

(defun ak/delete-buffer-list (buffer)
  "Delete buffer if exists"
  (when (get-buffer buffer)
    (kill-buffer buffer)))

(defun ak/save-exit-buffer-list ()
  "save all buffers in list then close them. Used for keeping gtd from conflicting on multiple machines"
  (interactive)
  (save-some-buffers gtd-buffer-list)
  (mapcar #'ak/delete-buffer-list gtd-buffer-list))
#+end_src

#+RESULTS:
: ak/save-exit-buffer-list
